version: "3.3"

services:
  caddy:
    image: caddy:2.4.3-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "3000:3000"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      # - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    network_mode: "host"

volumes:
  caddy_data:
  caddy_config: